services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wp-nginx-vol:/var/www/html
    ports:
      - '8080:80'
    networks:
      - nginx-wp-net
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:4.7.1-php7.0-fpm
    expose:
      - '9000'
    volumes:
      - wp-nginx-vol:/var/www/html
    env_file:
      - ../secrets/wordpress/.env
    networks:
      - nginx-wp-net
      - wp-mariadb-net
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ../secrets/mariadb/.env
    networks:
      - wp-mariadb-net
    restart: always

volumes:
  wp-nginx-vol: # need to be in /home/ncasteln/data
  db-data: # need to be in /home/ncasteln/data

networks:
  nginx-wp-net:
  wp-mariadb-net: