# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  webserver:
    init: true
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - wp_nginx_data:/var/www/html
    ports:
      - '443:443'
    depends_on:
      - cms
    networks:
      nginx_wp_net:
        aliases:
          - nginx_ip_address

  cms:
    init: true
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    secrets:
      - wordpress_secrets
    expose:
      - '9000'
    volumes:
      - wp_nginx_data:/var/www/html
    depends_on:
      - database
    networks:
      nginx_wp_net:
        aliases:
          - wordpress_ip
      mariadb_wp_net:
        aliases:
          - wordpress_ip

  database:
    init: true
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - ../secrets/mariadb/.env
    expose:
      - '3306'
    # volumes:
    #  - mariadb_data:/var/lib/mysql
    networks:
      mariadb_wp_net:
        aliases:
          - mariadb_ip

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8085:80"
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   networks:
  #     - nginx_wp_net
  #     - mariadb_wp_net
  #   restart: always

volumes:
  wp_nginx_data: # need to be in /home/ncasteln/data
  mariadb_data: # need to be in /home/ncasteln/data

networks:
  nginx_wp_net:
  mariadb_wp_net:

secrets:
  wordpress_secrets:
    file: ../secrets/wordpress/.env
