services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 9000
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306