# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  webserver:
    init: true
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - wp-nginx-vol:/var/www/html
    ports:
      - '443:443'
    depends_on:
      - cms
    networks:
      nginx-wp-net:
        aliases:
          - nginx_ip_address

  cms:
    init: true
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - ../secrets/wordpress/.env
    expose:
      - '9000'
    volumes:
      - wp-nginx-vol:/var/www/html
    depends_on:
      - database
    networks:
      nginx-wp-net:
        aliases:
          - wp_ip
      mariadb-wp-net:
        aliases:
          - wp_ip

  database:
    init: true
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - ../secrets/mariadb/.env
    expose:
      - '3306'
    # volumes:
    #  - mariadb-data:/var/lib/mysql
    networks:
      mariadb-wp-net:
        aliases:
          - mariadb_ip

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8085:80"
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   networks:
  #     - nginx-wp-net
  #     - mariadb-wp-net
  #   restart: always

volumes:
  wp-nginx-vol: # need to be in /home/ncasteln/data
  mariadb-data: # need to be in /home/ncasteln/data

networks:
  nginx-wp-net:
  mariadb-wp-net:
