# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - wp_nginx_data:/var/www/html
    ports:
      - '443:443'
    depends_on:
      - wordpress
      # wordpress:
      #   condition: service_healthy
    networks:
      - nginx_wp_net

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    secrets:
      - wordpress_secrets
    expose:
      - '9000'
    volumes:
      - wp_nginx_data:/var/www/html
    depends_on:
      - mariadb
      # mariadb:
      #   condition: service_healthy
    networks:
      nginx_wp_net:
        aliases:
          - wordpress_ip
      mariadb_wp_net:
    # healthcheck:
    #   test: ["CMD-SHELL", "wp core is-installed --allow-root --path=/var/www/html/localhost/public_html"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    secrets:
      - mariadb_secrets
    expose:
      - '3306'
    # volumes:
    #  - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_wp_net
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3

volumes:
  wp_nginx_data: # need to be in /home/ncasteln/data
  # mariadb_data: # need to be in /home/ncasteln/data

networks:
  nginx_wp_net:
  mariadb_wp_net:

secrets:
  wordpress_secrets:
    file: ../secrets/wordpress/.env
  mariadb_secrets:
    file: ../secrets/mariadb/.env
