# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wp_nginx_vol:/var/www/html
    ports:
      - '443:443'
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - nginx_wordpress_net
    restart: always
    init: true

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        WP_DOMAIN: ${WP_DOMAIN}
    volumes:
      - wp_nginx_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - nginx_wordpress_net
      - mariadb_wordpress_net
    environment:
      WP_DOMAIN: ${WP_DOMAIN}
      WP_SECRETS: ${WP_SECRETS}
    secrets:
      - wp_secrets
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/html/${WP_DOMAIN}/public_html"]
      start_period: 7s
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always
    init: true

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - mariadb_wordpress_net
    environment:
      DB_SECRETS: /run/secrets/db_secrets
    secrets:
      - db_secrets
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping" ]
      start_period: 7s
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always
    init: true

volumes:
  wp_nginx_vol:
    name: wp_nginx_vol
    # driver_opts:
    #   type: volume
    #   o: bind
    #   device: ${WP_DATA}
  mariadb_vol:
    name: mariadb_vol
    # driver_opts:
    #   type: volume
    #   o: bind
    #   device: ${DB_DATA}

networks:
  nginx_wordpress_net:
    name: inception_frontend
  mariadb_wordpress_net:
    name: inception_backend

secrets:
  wp_secrets:
    file: ../secrets/wordpress/.env #customize
  db_secrets:
    file: ../secrets/mariadb/.env #customize
