# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp_nginx_vol:/var/www/html
    ports:
      - '443:443'
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - nginx_wordpress_net
    restart: always
    init: true

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp_nginx_vol:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - nginx_wordpress_net
      - mariadb_wordpress_net
    secrets:
      - wordpress_secrets
    environment:
      WP_SECRETS: /run/secrets/wordpress_secrets
      WP_DOMAIN: ncasteln.42.fr
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/html/ncasteln.42.fr/public_html"]
      start_period: 7s
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always
    init: true

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - mariadb_wordpress_net
    secrets:
      - mariadb_secrets
    environment:
      MARIADB_SECRETS: /run/secrets/mariadb_secrets
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      start_period: 7s
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always
    init: true

# volumes:
#   wp_nginx_vol:
#     name: wp_nginx_vol
#     driver_opts:
#       type: bind
#       device: /home/ncasteln/data/wp_data
#   mariadb_vol:
#     name: mariadb_vol
#     driver_opts:
#       type: bind
#       device: /home/ncasteln/data/db_data

volumes:
  wp_nginx_vol:
    name: wp_nginx_vol
    driver_opts:
      type: none
      device: /home/ncasteln/data/wp_data
      o: bind
  mariadb_vol:
    name: mariadb_vol
    driver_opts:
      type: none
      device: /home/ncasteln/data/db_data
      o: bind

# volumes:
#   wp_nginx_vol:
#     name: wp_nginx_vol
#   mariadb_vol:
#     name: mariadb_vol

networks:
  nginx_wordpress_net:
    name: inception_frontend
  mariadb_wordpress_net:
    name: inception_backend

secrets:
  wordpress_secrets:
    file: ../secrets/wordpress/.env
  mariadb_secrets:
    file: ../secrets/mariadb/.env
