# https://github.com/compose-spec/compose-spec/blob/master/spec.md

version: '2.2.3'

services:
  nginx:
    init: true
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - ../data/nginx-wp/:/var/www/html
      # - wp_nginx_data:/var/www/html
    ports:
      - '443:443'
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - nginx_wordpress
    restart: always

  wordpress:
    init: true
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - ../data/nginx-wp/:/var/www/html
      # - wp_nginx_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - nginx_wordpress
      - mariadb_wordpress
    secrets:
      - wordpress_secrets
    environment:
      WP_SECRETS: /run/secrets/wordpress_secrets
      WP_DOMAIN: localhost
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/html/localhost/public_html"]
      start_period: 5s
      interval: 2s
      timeout: 2s
      retries: 3
    restart: always

  mariadb:
    init: true
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - ../data/nginx-wp/:/var/www/html
      # - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_wordpress
    secrets:
      - mariadb_secrets
    environment:
      MARIADB_SECRETS: /run/secrets/mariadb_secrets
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      start_period: 5s
      interval: 2s
      timeout: 2s
      retries: 3
    restart: always

# volumes:
#   wp_nginx_data:
#   mariadb_data:

networks:
  nginx_wordpress:
    name: inception_frontend
  mariadb_wordpress:
    name: inception_backend

secrets:
  wordpress_secrets:
    file: ../secrets/wordpress/.env
  mariadb_secrets:
    file: ../secrets/mariadb/.env
