services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wp-nginx-vol:/var/www/html
    ports:
      - '443:443'
    networks:
      - nginx-wp-net
    restart: always

  wordpress:
    container_name: wordpress
    # image: wordpress:4.7.1-php7.0-fpm
    #image: wordpress:6.5.3-php8.1-fpm
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - '9000'
    volumes:
      - wp-nginx-vol:/var/www/html
    env_file:
      - ../secrets/wordpress/.env
    networks:
      - nginx-wp-net
      - wp-mariadb-net
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - '3306'
    # volumes:
    #  - db-data:/var/lib/mysql
    env_file:
      - ../secrets/mariadb/.env
    networks:
      - wp-mariadb-net
    restart: always

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: myrootpassword
  #   networks:
  #     - nginx-wp-net
  #     - wp-mariadb-net
  #   restart: always

volumes:
  wp-nginx-vol: # need to be in /home/ncasteln/data
  db-data: # need to be in /home/ncasteln/data

networks:
  nginx-wp-net:
  wp-mariadb-net: