version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_mariadb_HOST: mariadb:3306
      WORDPRESS_mariadb_USER: wordpress
      WORDPRESS_mariadb_PASSWORD: wordpress_password
      WORDPRESS_mariadb_NAME: wordpress
    restart: always

  mariadb:
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    restart: always

volumes:
  mariadb_data: {}
  wordpress_data: {}