FROM debian:bullseye

RUN apt-get update -y

RUN ./tools/install_wp.sh

# install wget and wordpress
# RUN apt-get install wget -y
# RUN wget https://wordpress.org/latest.tar.gz
# RUN tar -xzvf latest.tar.gz
# needs