version: '3'

services:
  mariadb:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: mypassword
    restart: always
  wp:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - /data/html"/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: dbname
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_TABLE_PREFIX: wp_
      MYSQL_ROOT_PASSWORD: myrootpass
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: always
  nginx:
    image: nginx:stable-alpine
    volumes:
      - nginx:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wp